In [1]:
#configuration
import numpy as np

In [20]:
data = [6,7,8,9]
data2 = [[1,2],[3,4]]
data3 = [data,data]
print data3
print data3*3
arr1 = np.array(data3)
print arr1.dtype
print arr1.shape

[[6, 7, 8, 9], [6, 7, 8, 9]]
[[6, 7, 8, 9], [6, 7, 8, 9], [6, 7, 8, 9], [6, 7, 8, 9], [6, 7, 8, 9], [6, 7, 8, 9]]


(2, 4)

In [40]:
np.zeros(10)
np.zeros((3,6))
np.empty((2,4)) #returns garbage
arr1 = np.array([1,2,3], dtype = np.float64)
print arr1
int_array = np.arange(10)
print int_array
str_array = np.array(int_array, dtype = np.string_)
print str_array
print 1.0/int_array

[ 1.  2.  3.]
[0 1 2 3 4 5 6 7 8 9]
['0' '1' '2' '3' '4' '5' '6' '7' '8' '9']
[        inf  1.          0.5         0.33333333  0.25        0.2
  0.16666667  0.14285714  0.125       0.11111111]


/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:10: RuntimeWarning: divide by zero encountered in divide


In [57]:
data = np.random.rand(7,4)
values = np.array(range(7))
data[values == 2,2]
data[ ~(values == 2), 2:]


array([[ 0.33899792,  0.39648871],
       [ 0.35258478,  0.48669018],
       [ 0.28004743,  0.00705501],
       [ 0.6076632 ,  0.55922154],
       [ 0.89396804,  0.92257897],
       [ 0.04836557,  0.94792387]])